option('gsettings', type: 'boolean', value: true, description: 'Build the GSettings configuration backend.')
option('spatial', type: 'boolean', value: true, description: 'Build the spatial overview plugin.')
option('night-light', type: 'boolean', value: true, description: 'Build the night light plugin.')
